notifications:
  email: false

branches:
  only:
    - master

language: python
os: linux
dist: xenial

jobs:
  allow_failures:
    - stage: lint

  include:
    - stage: lint
      name: "Black"
      language: python
      python: "3.7"
      install: pip install black
      script: black --check youtokentome
    
    - stage: test
      name: "Python unit tests"
      language: python
      python: "3.7"
      install:
        - pip install pytest==4.3.1 tabulate==0.8.5
        - python setup.py install
      script:
        - cd tests/unit_tests
        - pytest

    - stage: build
      name: "Linux wheels building"
      services:
        - docker
      language: python
      python: "3.7"
      env:
        - CIBW_SKIP="cp27-* cp33-* cp34-* *win* *i686*"

    - name: "macOS wheels building"
      os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - brew update
        - brew install gcc@8
      env:
        - MACOSX_DEPLOYMENT_TARGET=10.14
        - CIBW_SKIP="cp27-* cp33-* cp34-* *win* *i686*"
        - CXX="g++-8"
        - CC="gcc-8"

install:
  - pip install -U pip
  - pip install cibuildwheel==0.12 twine==1.15.0

script:
  - cibuildwheel --output-dir wheelhouse
  - ls -l wheelhouse
  - |
    if [ ! -z $TRAVIS_TAG ]; then
      rm -rf dist && python setup.py sdist
      twine upload -u $PYPI_USER -p $PYPI_TOKEN --skip-existing dist/*.tar.gz wheelhouse/*.whl
    fi
